"""
import implementQueue as iq

myqueue = iq.queue()
print(myqueue.pop())
myqueue.push("avvaiyar")
print(myqueue.pop())
print(myqueue.peek())
myqueue.push("avvaiyar")
print(myqueue.peek())
myqueue.push("oonai")
myqueue.push("otagam")
myqueue.push("aeni")
myqueue.push("eli")
print(myqueue.peek())
myqueue.push("eee")
myqueue.push("elai")
myqueue.push("aadu")
myqueue.push("amma")
print(myqueue.peek())
myqueue.display()
"""


import queues.implementQueueUsingStacks as iqus

myqueue = iqus.queueWithStack()
print(myqueue.dequeue())
myqueue.enqueue("avvaiyar")
print(myqueue.dequeue())
#print(myqueue.peek())
myqueue.enqueue("avvaiyar")
#print(myqueue.peek())
myqueue.enqueue("oonai")
myqueue.enqueue("otagam")
myqueue.enqueue("aeni")
myqueue.enqueue("eli")
#print(myqueue.peek())
myqueue.display()
myqueue.enqueue("eee")
myqueue.enqueue("elai")
myqueue.enqueue("aadu")
myqueue.enqueue("amma")
#print(myqueue.peek())
myqueue.display()
